export const ESTADOS_CIUDADES: Record<string, string[]> = {
  "Aguascalientes": [
    "Aguascalientes", "Jesús María", "Calvillo", "Pabellón de Arteaga", "Rincón de Romos",
    "San Francisco de los Romo", "Asientos", "Tepezalá", "Cosío", "El Llano", "Ojuelos de Jalisco"
  ],
  "Baja California": [
    "Tijuana", "Mexicali", "Ensenada", "Rosarito", "Tecate", "San Quintín", "San Felipe",
    "Valle de Guadalupe", "Maneadero", "El Sauzal", "Punta Colonet", "Colonia Guerrero",
    "Vicente Guerrero", "Camalu", "San Vicente", "Ojos Negros", "Guadalupe Victoria",
    "Algodones", "Progreso", "Ciudad Morelos", "Ejido Puebla", "Tijuana Centro"
  ],
  "Baja California Sur": [
    "La Paz", "Los Cabos", "Cabo San Lucas", "San José del Cabo", "Loreto",
    "Mulegé", "Comondú", "Santa Rosalía", "San Ignacio", "Guerrero Negro",
    "Ciudad Constitución", "Ciudad Insurgentes", "Todos Santos", "El Pescadero",
    "Los Barriles", "Buena Vista", "La Ribera", "Miraflores", "Santiago",
    "Cabo Pulmo", "El Triunfo", "San Antonio", "San Bartolo", "Villa Morelos",
    "Puerto San Carlos", "Puerto López Mateos", "Santa Rita", "Bahía Tortugas",
    "Punta Abreojos", "Santa Rosalía de Mulegé", "Villa Alberto Alvarado Araiza"
  ],
  "Campeche": [
    "Campeche", "Ciudad del Carmen", "Champotón", "Escárcega", "Calkiní",
    "Hecelchakán", "Hopelchén", "Palizada", "Seybaplaya", "Candelaria",
    "Tenabo", "Holpechén", "Dzibalchén", "Sabancuy", "Isla Aguada",
    "El Tigre", "Xpujil", "Constitución", "Carrizal", "Pomuch"
  ],
  "Chiapas": [
    "Tuxtla Gutiérrez", "San Cristóbal de las Casas", "Tapachula", "Palenque",
    "Comitán", "Ocosingo", "Villaflores", "Chiapa de Corzo", "Tonalá",
    "Arriaga", "Pichucalco", "Simojovel", "Bochil", "San Fernando",
    "Huixtla", "Motozintla", "Cintalapa", "Jiquipilas", "Acala",
    "Venustiano Carranza", "La Concordia", "Ángel Albino Corzo", "Mapastepec",
    "Pijijiapan", "Reforma", "Ostuacán", "Pueblo Nuevo Solistahuacán",
    "Berriozábal", "Suchiapa", "Chiapilla", "Tzimol", "Las Margaritas"
  ],
  "Chihuahua": [
    "Chihuahua", "Ciudad Juárez", "Delicias", "Cuauhtémoc", "Parral",
    "Nuevo Casas Grandes", "Camargo", "Jiménez", "Guachochi", "Meoqui",
    "Bocoyna", "Aldama", "Allende", "Aquiles Serdán", "Ascensión",
    "Balleza", "Batopilas", "Buenaventura", "Casas Grandes", "Carichí",
    "Coyame del Sotol", "Cusihuiriachi", "El Tule", "Gran Morelos", "Guadalupe",
    "Guadalupe y Calvo", "Guazapares", "Gómez Farías", "Hidalgo del Parral",
    "Huejotitán", "Ignacio Zaragoza", "Janos", "Julimes", "López",
    "Madera", "Maguarichi", "Manuel Benavides", "Matachí", "Matamoros",
    "Morelos", "Moris", "Namiquipa", "Nonoava", "Ocampo", "Ojinaga",
    "Praxedis G. Guerrero", "Riva Palacio", "Rosales", "Rosario", "San Francisco de Borja",
    "San Francisco de Conchos", "San Francisco del Oro", "Santa Bárbara", "Santa Isabel",
    "Satevó", "Saucillo", "Temósachi", "Urique", "Uruachi", "Valle de Zaragoza"
  ],
  "CDMX": [
    "Álvaro Obregón", "Azcapotzalco", "Benito Juárez", "Coyoacán",
    "Cuajimalpa", "Cuauhtémoc", "Gustavo A. Madero", "Iztacalco",
    "Iztapalapa", "Magdalena Contreras", "Miguel Hidalgo", "Milpa Alta",
    "Tláhuac", "Tlalpan", "Venustiano Carranza", "Xochimilco",
    "Santa Fe", "Polanco", "Roma Norte", "Roma Sur", "Condesa",
    "Coyoacán Centro", "Del Valle", "Narvarte", "Pedregal", "Tepito",
    "Tlatelolco", "Doctores", "Escandón", "Juárez", "Anzures",
    "Lomas de Chapultepec", "Peralvillo", "Guerrero", "Aragón",
    "San Ángel", "Copilco", "Peña Blanca", "Xochimilco Centro"
  ],
  "Coahuila": [
    "Saltillo", "Torreón", "Monclova", "Piedras Negras", "Acuña",
    "Ramos Arizpe", "Matamoros", "San Pedro", "Múzquiz", "Sabinas",
    "Frontera", "Allende", "Arteaga", "Candela", "Castaños",
    "Francisco I. Madero", "General Cepeda", "Guerrero", "Hidalgo",
    "Jiménez", "Juárez", "Lamadrid", "Nava", "Ocampo",
    "Parras de la Fuente", "Progreso", "Nadadores", "San Buenaventura",
    "Sierra Mojada", "Viesca", "Villa Unión", "Zaragoza",
    "Torreon", "Ciudad Acuña", "Nueva Rosita"
  ],
  "Colima": [
    "Colima", "Manzanillo", "Tecomán", "Villa de Álvarez", "Comala",
    "Armería", "Cuauhtémoc", "Coquimatlán", "Minatitlán", "Ixtlahuacán",
    "Jalipa", "El Chanal", "Cofradía de Juárez", "Quesería",
    "Cómala", "Nogueras", "Suchitlán"
  ],
  "Durango": [
    "Durango", "Gómez Palacio", "Lerdo", "Santiago Papasquiaro", "Guadalupe Victoria",
    "Pueblo Nuevo", "El Salto", "Vicente Guerrero", "Nombre de Dios",
    "Canatlán", "Canatlan", "Coneto de Comonfort", "Cuencamé", "El Oro",
    "General Simón Bolívar", "Guanaceví", "Hidalgo", "Indé", "Mapimí",
    "Mezquital", "Nazas", "Nuevo Ideal", "Ocampo", "Otáez",
    "Pánuco de Coronado", "Peñón Blanco", "Poanas", "Rodeo", "San Bernardo",
    "San Dimas", "San Juan de Guadalupe", "San Juan del Río", "San Luis del Cordero",
    "San Pedro del Gallo", "Santa Clara", "Súchil", "Tamazula", "Tepehuanes",
    "Tlahualilo", "Topia", "Canatlan", "Guarismo"
  ],
  "Estado de México": [
    "Toluca", "Ecatepec", "Naucalpan", "Tlalnepantla", "Metepec",
    "Nezahualcóyotl", "Cuautitlán Izcalli", "Chalco", "Texcoco", "Chimalhuacán",
    "Ixtapaluca", "Atizapán", "Tultitlán", "Tecámac", "Valle de Chalco",
    "Amecameca", "Coacalco", "Cuautitlán", "Huixquilucan", "Lerma",
    "Nicolás Romero", "Ocoyoacac", "San Mateo Atenco", "Tultepec", "Zinacantepec",
    "Almoloya de Juárez", "Almoloya del Río", "Apaxco", "Atenco", "Atlacomulco",
    "Axapusco", "Ayapango", "Calimaya", "Capulhuac", "Coatepec Harinas",
    "Cocotitlán", "Coyotepec", "El Oro", "Huehuetoca", "Ixtapan de la Sal",
    "Ixtapan del Oro", "Jaltenco", "Jilotepec", "Jiquipilco", "Jocotitlán",
    "Joquicingo", "Juchitepec", "La Paz", "Luvianos", "Malinalco",
    "Melchor Ocampo", "Nopaltepec", "Ocuilan", "Otumba", "Otzoloapan",
    "Otzolotepec", "Ozumba", "Papalotla", "Polotitlán", "Rayón",
    "San Antonio la Isla", "San Felipe del Progreso", "San Martín de las Pirámides",
    "San Simón de Guerrero", "Santo Tomás", "Soyaniquilpan", "Sultepec",
    "Temascalapa", "Temascalcingo", "Temascaltepec", "Temoaya", "Tenancingo",
    "Tenango del Aire", "Tenango del Valle", "Teoloyucan", "Teotihuacán",
    "Tepetlaoxtoc", "Tepetlixpa", "Tepotzotlán", "Tequixquiac", "Texcalyacac",
    "Tezoyuca", "Tianguistenco", "Timilpan", "Tlalmanalco", "Tlaltelolco",
    "Tonatico", "Tultepec", "Valle de Bravo", "Villa del Carbón",
    "Villa Guerrero", "Villa Victoria", "Xonacatlán", "Zacazonapan",
    "Zacualpan", "Zinacanctepec", "Zumpahuacán", "Zumpango"
  ],
  "Guanajuato": [
    "León", "Irapuato", "Celaya", "Salamanca", "Guanajuato",
    "San Miguel de Allende", "Silao", "Pénjamo", "Dolores Hidalgo", "Valle de Santiago",
    "Acámbaro", "San Francisco del Rincón", "Abasolo", "Apaseo el Alto",
    "Apaseo el Grande", "Atarjea", "Comonfort", "Coroneo", "Cortazar",
    "Cuerámaro", "Doctor Mora", "Huanímaro", "Jaral del Progreso", "Jerécuaro",
    "Manuel Doblado", "Moroleón", "Ocampo", "Purísima del Rincón", "Romita",
    "Salvatierra", "San Diego de la Unión", "San Felipe", "San José Iturbide",
    "San Luis de la Paz", "Santa Catarina", "Santiago Maravatío", "Tarandacuao",
    "Tarimoro", "Tierra Blanca", "Uriangato", "Victoria", "Villagrán",
    "Xichú", "Yuriria"
  ],
  "Guerrero": [
    "Acapulco", "Chilpancingo", "Zihuatanejo", "Taxco", "Iguala",
    "Tlapa", "Chilapa", "Atoyac de Álvarez", "Ometepec", "Teloloapan",
    "Tixtla", "Petatlán", "Arcelia", "Ayutla de los Libres", "Azoyú",
    "Benito Juárez", "Buenavista de Cuéllar", "Coahuayutla de José María Izazaga",
    "Cocula", "Copala", "Copalillo", "Copanatoyac", "Coyuca de Benítez",
    "Coyuca de Catalán", "Cuajinicuilapa", "Cualác", "Cuautepec", "Cuetzala del Progreso",
    "Cutzamala de Pinzón", "Eduardo Neri", "Florencio Villarreal", "General Canuto A. Neri",
    "General Heliodoro Castillo", "Huamuxtitlán", "Huitzuco de los Figueroa",
    "Igualapa", "José Joaquín de Herrera", "Juan R. Escudero", "La Unión de Isidoro Montes de Oca",
    "Leonardo Bravo", "Malinaltepec", "Marquelia", "Mártir de Cuilapan",
    "Metlatónoc", "Mochitlán", "Olinalá", "Quechultenango", "San Marcos",
    "San Miguel Totolapan", "Tecoanapa", "Técpan de Galeana", "Tepecoacuilco de Trujano",
    "Tetipac", "Tlacoapa", "Tlalchapa", "Tlalixtaquilla de Maldonado", "Tlapenco",
    "Xalpatláhuac", "Xochihuehuetlán", "Xochistlahuaca", "Zapotitlán Tablas",
    "Zirándaro", "Zitlala", "José Azueta", "Ixtapa-Zihuatanejo"
  ],
  "Hidalgo": [
    "Pachuca", "Tulancingo", "Tula de Allende", "Ixmiquilpan", "Tizayuca",
    "Huejutla", "Tepeji del Río", "Actopan", "Mineral de la Reforma", "Zempoala",
    "Tepeapulco", "Atotonilco el Grande", "Atitalaquia", "Atotonilco de Tula",
    "Apan", "Almoloya", "Alfajayucan", "Acaxochitlán", "Acatlan",
    "Biznaga", "Cardonal", "Chapantongo", "Chapulhuacán", "Chilcuautla",
    "El Arenal", "Eloxochitlán", "Emiliano Zapata", "Epazoyucan", "Francisco I. Madero",
    "Huasca de Ocampo", "Huautla", "Huazalingo", "Huehuetla", "Huichapan",
    "Jacala de Ledezma", "Jaltocán", "Juárez Hidalgo", "La Misión", "Lolotla",
    "Metepec", "Metztitlán", "Mineral del Chico", "Mineral del Monte", "Molango",
    "Nicolás Flores", "Nopala de Villagrán", "Omitlán de Juárez", "Pacula",
    "Pisaflores", "Progreso de Obregón", "San Agustín Metzquititlán",
    "San Agustín Tlaxiaca", "San Bartolo Tutotepec", "San Felipe Orizatlán",
    "San Salvador", "Santiago de Anaya", "Santiago Tulantepec", "Singuilucan",
    "Tasquillo", "Tecozautla", "Tenango de Doria", "Tepehuacán de Guerrero",
    "Tepetitlán", "Tetepango", "Tezontepec de Aldama", "Tianguistengo",
    "Tlahuelilpan", "Tlahuiltepa", "Tlanalapa", "Tlanchinol", "Tlaxcoapan",
    "Tolcayuca", "Tonanitla", "Tulancingo de Bravo", "Villa de Tezontepec",
    "Xochiatipan", "Xochicoatlán", "Yahualica", "Zacualtipán de Ángeles",
    "Zapotlán de Juárez", "Zimapán"
  ],
  "Jalisco": [
    "Guadalajara", "Zapopan", "Tlaquepaque", "Puerto Vallarta", "Tonalá",
    "Tlajomulco", "Lagos de Moreno", "Tepatitlán", "Ciudad Guzmán", "Ocotlán",
    "Tala", "Arandas", "San Juan de los Lagos", "Ameca", "Autlán de Navarro",
    "El Salto", "Zapotlanejo", "La Barca", "Acatlán de Juárez", "Ahualulco de Mercado",
    "Ajijic", "Chapala", "Jocotepec", "Cihuatlán", "Cocula", "Colotlán",
    "Degollado", "El Grullo", "Etzatlán", "Guadalajara Centro", "Huejúcar",
    "Huejuquilla el Alto", "Jamay", "Jesús María", "Juchitlán", "La Huerta",
    "Mascota", "Mazamitla", "Mexticacán", "Mezquitic", "Ojuelos de Jalisco",
    "Pihuamo", "Poncitlán", "Puerto Vallarta Centro", "Purificación", "Quitupan",
    "San Cristóbal de la Barranca", "San Diego de Alejandría", "San Gabriel",
    "San Marcos", "San Martín de Bolaños", "San Martín Hidalgo", "San Miguel el Alto",
    "San Sebastián del Oeste", "Sayula", "Tala Centro", "Talpa de Allende",
    "Tamazula de Gordiano", "Tapalpa", "Tecalitlán", "Tecolotlán", "Tenamaxtlán",
    "Teocaltiche", "Teocuitatlán de Corona", "Tepatitlán de Morelos", "Tequila",
    "Tizapán el Alto", "Tlajomulco de Zúñiga", "Tolimán", "Tomatlán",
    "Tonaya", "Tonila", "Totatiche", "Tototlán", "Tuxcacuesco", "Tuxcueca",
    "Tuxpan", "Unión de San Antonio", "Unión de Tula", "Valle de Guadalupe",
    "Valle de Juárez", "Villa Corona", "Villa Guerrero", "Villa Hidalgo",
    "Villa Purificación", "Yahualica de González Gallo", "Zacoalco de Torres",
    "Zapotiltic", "Zapotitlán de Vadillo", "Zapotlán del Rey", "Zapotlán el Grande",
    "Jilotlán de los Dolores", "Nuevo Laredo", "San Juanito de Escobedo"
  ],
  "Michoacán": [
    "Morelia", "Uruapan", "Zamora", "Lázaro Cárdenas", "Apatzingán",
    "Pátzcuaro", "Zitácuaro", "Hidalgo", "La Piedad", "Sahuayo",
    "Zacapu", "Los Reyes", "Maravatío", "Tacámbaro", "Jiquilpan",
    "Jacona", "Puruarán", "Tuxpan", "Múgica", "Coalcomán",
    "Aguililla", "Álvaro Obregón", "Angamacutiro", "Angangueo", "Aporo",
    "Aquila", "Ario", "Arteaga", "Briseñas", "Buenavista",
    "Carácuaro", "Chilchota", "Chinicuila", "Chucándiro", "Churintzio",
    "Churumuco", "Coahuayana", "Copándaro", "Cotija", "Cuitzeo",
    "Charapan", "Charo", "Cherán", "Ecuandureo", "Epitacio Huerta",
    "Erongarícuaro", "Gabriel Zamora", "Huandacareo", "Huaniqueo", "Huetamo",
    "Huiramba", "Indaparapeo", "Irimbo", "Ixtlán", "Jiménez",
    "Juárez", "Jungapeo", "Lagunillas", "Madero", "Marcos Castellanos",
    "Morelos", "Nahuatzen", "Nocupétaro", "Nuevo Parangaricutiro", "Nuevo Urecho",
    "Numarán", "Ocampo", "Pajacuarán", "Panindícuaro", "Paracho",
    "Parácuaro", "Pedernales", "Peribán", "Purépero", "Puruarán",
    "Queréndaro", "Quiroga", "Régules", "Salvador Escalante", "San Lucas",
    "Santa Ana Maya", "Senguio", "Susupuato", "Tancítaro", "Tangamandapio",
    "Tangancícuaro", "Tanhuato", "Taretan", "Tarímbaro", "Tepalcatepec",
    "Tingambato", "Tingüindín", "Tiquicheo de Nicolás Romero", "Tlalpujahua",
    "Tlazazalca", "Tocumbo", "Tumbiscatío", "Turicato", "Tuzantla",
    "Tzintzuntzan", "Tzitzio", "Venustiano Carranza", "Villamar", "Vista Hermosa",
    "Yurécuaro", "Zaragoza", "Zinapécuaro", "Zináparo", "Ziracuaretiro"
  ],
  "Morelos": [
    "Cuernavaca", "Jiutepec", "Cuautla", "Temixco", "Yautepec",
    "Emiliano Zapata", "Ayala", "Xochitepec", "Puente de Ixtla", "Jojutla",
    "Tlaltizapán", "Axochiapan", "Coatlán del Río", "Huitzilac", "Jantetelco",
    "Jonacatepec", "Mazatepec", "Miacatlán", "Ocuituco", "Tetecala",
    "Tepalcingo", "Tetela del Volcán", "Totolapan", "Tlaquiltenango",
    "Temoac", "Zacatepec", "Zacualpan de Amilpas"
  ],
  "Nayarit": [
    "Tepic", "Bahía de Banderas", "Compostela", "Santiago Ixcuintla", "Nuevo Nayarit",
    "Tecuala", "Xalisco", "Acaponeta", "Ixtlán del Río", "Tuxpan",
    "Ruiz", "Ahuacatlán", "Amatlán de Cañas", "Del Nayar", "El Nayar",
    "Huajicori", "Jala", "La Yesca", "Rosamorada", "San Blas",
    "San Pedro Lagunillas", "Santa María del Oro", "Bucerías", "Cruz de Huanacaxtle",
    "La Cruz de Huanacaxtle", "Sayulita", "Punta Mita", "El Monteón",
    "Guayabitos", "La Peñita de Jaltemba", "Los Ayala", "Rincón de Guayabitos",
    "San Francisco (Sayulita)", "Mezcales", "Navarrete", "Valle de Banderas"
  ],
  "Nuevo León": [
    "Monterrey", "San Pedro Garza García", "San Nicolás de los Garza", "Apodaca",
    "Guadalupe", "Escobedo", "Santa Catarina", "Linares", "García", "Juárez",
    "Cadereyta", "Pesquería", "Allende", "Anáhuac", "Aramberri",
    "Cerralvo", "China", "Doctor Arroyo", "Doctor Coss", "Doctor González",
    "El Carmen", "Galeana", "General Bravo", "General Escobedo", "General Terán",
    "General Treviño", "General Zaragoza", "General Zuazua", "Hidalgo",
    "Higueras", "Hualahuises", "Iturbide", "Lampazos de Naranjo",
    "Los Aldamas", "Los Herreras", "Los Ramones", "Marín", "Melchor Ocampo",
    "Mier y Noriega", "Mina", "Montemorelos", "Parás", "Rayones",
    "Sabinas Hidalgo", "Salinas Victoria", "San Nicolás de los Garza",
    "Santiago", "Vallecillo", "Villaldama", "Zuazua"
  ],
  "Oaxaca": [
    "Oaxaca de Juárez", "Salina Cruz", "Juchitán", "Tuxtepec", "Puerto Escondido",
    "Huatulco", "Tehuantepec", "Santa Cruz Xoxocotlán", "Huajuapan de León",
    "Loma Bonita", "Tlaxiaco", "Miahuatlán", "Pochutla", "Pinotepa Nacional",
    "Ejutla de Crespo", "Etla", "Ixtepec", "Ixtlán de Juárez", "Jalapa del Marqués",
    "Jamiltepec", "Juxtlahuaca", "Matías Romero", "Nochixtlán", "Ocotlán de Morelos",
    "Puerto Ángel", "Putla Villa de Guerrero", "Río Grande", "San Bartolo Coyotepec",
    "San Juan Bautista Tuxtepec", "San Juan del Estado", "San Marcos Tlapazola",
    "San Martín Tilcajete", "San Pablo Villa de Mitla", "Santa Cruz Huatulco",
    "Santo Domingo Tehuantepec", "Santos Reyes Nopala", "Sola de Vega",
    "Teotitlán del Valle", "Tlacolula de Matamoros", "Tlacotepec Plumas",
    "Unión Hidalgo", "Xoxocotlán", "Yanhuitlán", "Zaachila", "Zimatlán de Álvarez"
  ],
  "Puebla": [
    "Puebla", "Tehuacán", "Atlixco", "San Martín Texmelucan", "Cholula",
    "Teziutlán", "Huauchinango", "Izúcar de Matamoros", "Amozoc", "Zacatlán",
    "Ajalpan", "Tecamachalco", "Acajete", "Acatlán", "Acatzingo",
    "Acteopan", "Ahuacatlán", "Ahuatlán", "Ahuazotepec", "Ahuehuetitla",
    "Altepexi", "Amixtlán", "Amozoc", "Aquixtla", "Atempan",
    "Atexcal", "Atlixco Centro", "Atoyatempan", "Atzala", "Atzitzihuacán",
    "Atzitzintla", "Axutla", "Ayotoxco de Guerrero", "Calpan", "Caltepec",
    "Camocuautla", "Caxhuacan", "Chalchicomula de Sesma", "Chapulco",
    "Chiautla", "Chiautzingo", "Chichiquila", "Chiconcuautla", "Chietla",
    "Chigmecatitlán", "Chignahuapan", "Chignautla", "Chila", "Chila de la Sal",
    "Chilchotla", "Chinantla", "Coatepec", "Coatzingo", "Cohetzala",
    "Cohuecan", "Coronango", "Coxcatlán", "Coyomeapan", "Coyotepec",
    "Cuapiaxtla de Madero", "Cuautempan", "Cuautinchán", "Cuautlancingo",
    "Cuayuca de Andrade", "Cuetzalan del Progreso", "Cuyoaco", "Domingo Arenas",
    "Eloxochitlán", "Epatlán", "Esperanza", "Francisco Z. Mena",
    "General Felipe Ángeles", "Guadalupe", "Guadalupe Victoria",
    "Hermenegildo Galeana", "Honey", "Huaquechula", "Huatlatlauca",
    "Hueyapan", "Hueytamalco", "Hueytlalpan", "Huitzilan de Serdán",
    "Huitziltepec", "Ixcamilpa de Guerrero", "Ixcaquixtla", "Ixtacamaxtitlán",
    "Ixtepec", "Jolalpan", "Jonotla", "Jopala", "Juan C. Bonilla",
    "Juan Galindo", "Juan N. Méndez", "La Magdalena Tlatlauquitepec",
    "Lafragua", "Libres", "Los Reyes de Juárez", "Mazapiltepec de Juárez",
    "Mixtla", "Molcaxac", "Naupan", "Nauzontla", "Nealtican",
    "Nicolás Bravo", "Nopalucan", "Ocotepec", "Ocoyucan", "Olinalá",
    "Olintla", "Oriental", "Pahuatlán", "Palmar de Bravo", "Pantepec",
    "Petlalcingo", "Piaxtla", "Puebla Centro", "Quecholac", "Quimixtlán",
    "Rafael Lara Grajales", "Reyes de Juárez", "San Andrés Cholula",
    "San Antonio Cañada", "San Diego la Mesa Tochimiltzingo", "San Felipe Teotlalcingo",
    "San Felipe Tepatlán", "San Gabriel Chilac", "San Gregorio Atzompa",
    "San Jerónimo Tecuanipan", "San Jerónimo Xayacatlán", "San José Chiapa",
    "San José Miahuatlán", "San Juan Atenco", "San Juan Atzompa",
    "San Martín Texmelucan Centro", "San Martín Totoltepec", "San Matías Tlalancaleca",
    "San Miguel Ixitlán", "San Miguel Xoxtla", "San Nicolás Buenos Aires",
    "San Nicolás de los Ranchos", "San Pablo Anicano", "San Pedro Cholula",
    "San Pedro Yeloixtlahuaca", "San Salvador el Seco", "San Salvador el Verde",
    "San Salvador Huixcolotla", "San Sebastián Tlacotepec", "Santa Catarina Tlaltempan",
    "Santa Inés Ahuatempan", "Santa Isabel Cholula", "Santiago Miahuatlán",
    "Santo Tomás Hueyotlipan", "Soltepec", "Tecali de Herrera",
    "Tecamachalco Centro", "Tecomatlán", "Tehuitzingo", "Tenampulco",
    "Teopantlán", "Teotlalco", "Tepango de Rodríguez", "Tepatlaxco de Hidalgo",
    "Tepeaca", "Tepemaxalco", "Tepeojuma", "Tepetzintla", "Tepexco",
    "Tepexi de Rodríguez", "Tepeyahualco", "Tepeyahualco de Cuauhtémoc",
    "Tetela de Ocampo", "Teteles de Ávila Castillo", "Teziutlán Centro",
    "Tianguismanalco", "Tilapa", "Tlahuapan", "Tlaltenango", "Tlanepantla",
    "Tlaola", "Tlapacoya", "Tlapanalá", "Tlatlauquitepec", "Tlaxco",
    "Tochimilco", "Tochtepec", "Totoltepec de Guerrero", "Tulcingo",
    "Tuzamapan de Galeana", "Tzicatlacoyan", "Venustiano Carranza",
    "Vicente Guerrero", "Xayacatlán de Bravo", "Xicotepec", "Xicotlán",
    "Xiutetelco", "Xochiapulco", "Xochiltepec", "Xochitlán de Vicente Suárez",
    "Xochitlán Todos Santos", "Yaonahuac", "Yehualtepec", "Zacapala",
    "Zacapoaxtla", "Zacatlán Centro", "Zapotitlán", "Zapotitlán de Méndez",
    "Zárate", "Zempoala", "Zoquiapan", "Zoquitlán"
  ],
  "Querétaro": [
    "Santiago de Querétaro", "San Juan del Río", "Corregidora", "El Marqués",
    "Tequisquiapan", "Pedro Escobedo", "Cadereyta de Montes", "Amealco",
    "Jalpan de Serra", "Ezequiel Montes", "Arroyo Seco", "Colón",
    "Huimilpan", "Landa de Matamoros", "Peñamiller", "Pinal de Amoles",
    "San Joaquín", "Tolimán", "Querétaro Centro", "Juriquilla", "El Pueblito",
    "Bernal", "Cadereyta", "Tequisquiapan Centro"
  ],
  "Quintana Roo": [
    "Cancún", "Playa del Carmen", "Chetumal", "Tulum", "Cozumel",
    "Isla Mujeres", "Puerto Morelos", "Felipe Carrillo Puerto", "Bacalar",
    "José María Morelos", "Akumal", "Holbox", "Cobá", "Kantunilkín",
    "Leona Vicario", "Mahahual", "Othón P. Blanco", "Puerto Juárez",
    "Solidaridad", "Benito Juárez", "Lázaro Cárdenas", "Nicolás Bravo",
    "Puerto Aventuras", "Xcaret", "Xel-Há", "El Cuyo", "Valladolid",
    "Isla Contoy", "Chiquilá"
  ],
  "San Luis Potosí": [
    "San Luis Potosí", "Ciudad Valles", "Soledad de Graciano Sánchez", "Matehuala",
    "Rioverde", "Tamazunchale", "Xilitla", "Ébano", "Cárdenas", "Santa María del Río",
    "Ahualulco", "Alaquines", "Aquismón", "Armadillo de los Infante",
    "Axtla de Terrazas", "Cardenas", "Cedral", "Cerritos", "Cerro de San Pedro",
    "Charcas", "Ciudad Fernández", "Coxcatlán", "El Naranjo", "Guadalcázar",
    "Huehuetlán", "Lagunillas", "Matlapa", "Mexquitic de Carmona", "Moctezuma",
    "Rayón", "Salinas", "San Antonio", "San Martín Chalchicuautla",
    "San Nicolás Tolentino", "San Vicente Tancuayalab", "Santa Catarina",
    "Santa Cruz de Juventino Rosas", "Santo Domingo", "Tamasopo", "Tampamolón Corona",
    "Tancanhuitz", "Tanlajás", "Tanquián de Escobedo", "Tierra Nueva",
    "Uquisio", "Vanegas", "Venado", "Villa de Arista", "Villa de Arriaga",
    "Villa de Guadalupe", "Villa de la Paz", "Villa de Ramos", "Villa de Reyes",
    "Villa Hidalgo", "Villa Juárez", "Zaragoza", "Wadley"
  ],
  "Sinaloa": [
    "Mazatlán", "Culiacán", "Los Mochis", "Guasave", "Navolato",
    "El Rosario", "Escuinapa", "Concordia", "El Fuerte", "Salvador Alvarado",
    "Guamúchil", "Choix", "Mocorito", "Ahome", "Angostura",
    "Badiraguato", "Cosalá", "Costa Rica", "El Verde", "Elota",
    "Escuinapa Centro", "Imala", "Isidoro Montes de Oca", "Mazatlán Centro",
    "Mochis Centro", "Mocorito Centro", "Pericos", "Quilá", "Rosario",
    "San Blas", "San Ignacio", "Sinaloa de Leyva", "Villa Unión",
    "Culiacán Centro", "La Cruz", "El Dorado", "Costa Azul", "Altata",
    "La Reforma", "Mármol", "Hacienda", "Cerros", "Tepuche",
    "Badiragüato", "Cosalá Centro", "Pueblo Nuevo"
  ],
  "Sonora": [
    "Hermosillo", "Ciudad Obregón", "Nogales", "Guaymas", "Navojoa",
    "San Luis Río Colorado", "Puerto Peñasco", "Caborca", "Agua Prieta", "Empalme",
    "Huatabampo", "Cananea", "Bácum", "Benito Juárez", "Benjamín Hill",
    "Carbó", "Cajeme", "Cucurpe", "Cumpas", "Divisaderos",
    "Empalme Centro", "Etchojoa", "Fronteras", "General Plutarco Elías Calles",
    "Granados", "Guaymas Centro", "Huachinera", "Huásabas", "Huépac",
    "Imuris", "La Colorada", "Magdalena de Kino", "Mazatán", "Moctezuma",
    "Naco", "Nácori Chico", "Nácori Grande", "Nanos", "Navojoa Centro",
    "Onavas", "Opodepe", "Oquitoa", "Pitiquito", "Quiriego",
    "Rayón", "Rosario", "Sahuaripa", "San Felipe de Jesús", "San Ignacio Río Muerto",
    "San Javier", "San Juan Bautista", "San Luis Río Colorado Centro", "San Miguel de Horcasitas",
    "San Pedro de la Cueva", "Santa Ana", "Santa Cruz", "Sáric",
    "Soyopa", "Suaqui Grande", "Tepache", "Trincheras", "Tubutama",
    "Ures", "Villa Hidalgo", "Villa Pesqueira", "Yécora", "Puerto Libertad",
    "Kino Bay", "Bahía de Kino", "Álamos", "Baviacora", "Arizpe"
  ],
  "Tabasco": [
    "Villahermosa", "Cárdenas", "Comalcalco", "Macuspana", "Paraíso",
    "Huimanguillo", "Cunduacán", "Centla", "Teapa", "Tenosique",
    "Balancán", "Emiliano Zapata", "Jalpa de Méndez", "Jonuta",
    "Nacajuca", "El Triunfo", "Chontalpa", "Frontera", "Jalpa",
    "Jalupa", "La Venta", "Ocuapan", "Playas del Rosario",
    "Reforma", "Tacotalpa"
  ],
  "Tamaulipas": [
    "Reynosa", "Tampico", "Matamoros", "Nuevo Laredo", "Ciudad Victoria",
    "Ciudad Madero", "Altamira", "El Mante", "Río Bravo", "Valle Hermoso",
    "San Fernando", "Abasolo", "Aldama", "Antiguo Morales", "Burgos",
    "Bustamante", "Camargo", "Casas", "Cruillas", "Díaz Ordaz",
    "Dolores", "Estación Manuel", "General Bravo", "González", "Güémez",
    "Guerrero", "Gustavo Díaz Ordaz", "Hidalgo", "Jaumave", "Jiménez",
    "Linares", "Llera", "Mainero", "Marina Madero", "Méndez",
    "Mier", "Miguel Alemán", "Miquihuana", "Nuevo Morelos", "Ocampo",
    "Padilla", "Palmillas", "Peñitas", "Pueblo Viejo", "Quebradas",
    "Reynosa Centro", "Soto la Marina", "Tampico Alto", "Tula",
    "Victoria", "Villagrán", "Xicoténcatl"
  ],
  "Tlaxcala": [
    "Tlaxcala", "Apizaco", "Huamantla", "Chiautempan", "Zacatelco",
    "San Pablo del Monte", "Calpulalpan", "Yauhquemehcan", "Papalotla",
    "Contla", "Amaxac de Guerrero", "Apetatitlán", "Atlangatepec",
    "Atltzayanca", "Benito Juárez", "Cuapiaxtla", "Cuaxomulco",
    "El Carmen Tequexquitla", "Emiliano Zapata", "Españita", "Ixtacuixtla de Mariano Matamoros",
    "Ixtenco", "Lázaro Cárdenas", "Mazatecochco de José María Morelos",
    "Muñoz de Domingo Arenas", "Nanacamilpa de Mariano Arista", "Natívitas",
    "Nativitas", "Ocotelulco", "Papalotla de Xicohténcatl", "Sanctórum de Lázaro Cárdenas",
    "San Damián Texóloc", "San Francisco Tetlanohcan", "San Jerónimo Zacualpan",
    "San José Teacalco", "San Juan Huactzinco", "San Lorenzo Axocomanitla",
    "San Lucas Tecopilco", "San Luis Apizaquito", "Santa Apolonia Teacalco",
    "Santa Catarina Ayometla", "Santa Cruz Quilehtla", "Santa Cruz Tlaxcala",
    "Santa Isabel Xiloxoxtla", "Tenancingo", "Teolocholco", "Tepeyanco",
    "Terrenate", "Tetla de la Solidaridad", "Tetlatlahuca", "Tlaxco",
    "Tocatlán", "Totolac", "Tzompantepec", "Xaloztoc", "Xaltocan",
    "Xicohtzinco", "Zitlaltepec de Trinidad Sánchez Santos"
  ],
  "Veracruz": [
    "Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Boca del Río",
    "Orizaba", "Poza Rica", "Minatitlán", "Tuxpan", "Papantla",
    "San Andrés Tuxtla", "Martínez de la Torre", "Acayucan", "Alvarado",
    "Álamo Temapache", "Amatlán de los Reyes", "Aquila", "Atlahuilco",
    "Atzacan", "Atzalan", "Ayahualulco", "Banderilla", "Benito Juárez",
    "Calcahualco", "Camaron de Tejeda", "Carrillo Puerto", "Castillo de Teayo",
    "Catemaco", "Cazones de Herrera", "Cerro Azul", "Chacaltianguis",
    "Chalma", "Chicoasén", "Chiconquiaco", "Chicontepec", "Chinameca",
    "Chinampa de Gorostiza", "Chocamán", "Chontla", "Coatepec",
    "Coatzintla", "Colipa", "Comapa", "Cotaxtla", "Coxquihui",
    "Coyutla", "Cuichapa", "Cuitláhuac", "El Higo", "Emiliano Zapata",
    "Espinal", "Filomeno Mata", "Fortín", "Gutierrez Zamora",
    "Hidalgotitlán", "Huatusco", "Huayacocotla", "Hueyapan de Ocampo",
    "Huiloapan de Cuauhtémoc", "Ignacio de la Llave", "Ilamatlán",
    "Isla", "Ixhuacán de los Reyes", "Ixhuatlán de Madero", "Ixhuatlán del Café",
    "Ixhuatlán del Sureste", "Ixmatlahuacan", "Ixtaczoquitlán",
    "Jalacingo", "Jalcomulco", "Jáltipan", "Jamapa", "Jesús Carranza",
    "Jilotepec", "José Azueta", "Juan Rodríguez Clara", "Juchique de Ferrer",
    "La Antigua", "La Perla", "Landero y Coss", "Las Choapas",
    "Las Minas", "Las Vigas de Ramírez", "Lerdo de Tejada", "Los Reyes",
    "Magdalena", "Maltrata", "Manlio Fabio Altamirano", "Mariano Escobedo",
    "Mecatlán", "Mecayapan", "Medellín de Bravo", "Miahuatlán",
    "Misantla", "Mixtla de Altamirano", "Moloacán", "Nanchital de Lázaro Cárdenas",
    "Naolinco", "Naranjal", "Naranjos Amatlán", "Nautla", "Nogales",
    "Oluta", "Omealca", "Orizaba Centro", "Otatitlán", "Oteapan",
    "Ozuluama de Mascareñas", "Pajapan", "Pánuco", "Paso de Ovejas",
    "Paso del Macho", "Perote", "Platón Sánchez", "Playa Vicente",
    "Poza Rica Centro", "Pueblo Viejo", "Puente Nacional", "Rafael Delgado",
    "Rafael Lucio", "Río Blanco", "Saltabarranca", "San Andrés Tenejapan",
    "San Andrés Tuxtla Centro", "San Juan Evangelista", "San Rafael",
    "Santiago Sochiapam", "Santiago Tuxtla", "Sayula de Alemán", "Soconusco",
    "Sochiapam", "Soledad de Doblado", "Soledad Atzompa", "Soteapan",
    "Tamalín", "Tamiahua", "Tampico Alto", "Tancoco", "Tantima",
    "Tantoyuca", "Tatahuicapan de Juárez", "Tatatila", "Tecolutla",
    "Tehuipango", "Tempoal", "Tenampa", "Tenochtitlán", "Teocelo",
    "Tepatlaxco", "Tepetlán", "Tepetzintla", "Tequila", "Texcatepec",
    "Texhuacán", "Texistepec", "Tezonapa", "Tierra Blanca", "Tihuatlán",
    "Tlacojalpan", "Tlacolulan", "Tlacotalpan", "Tlacotepec de Mejía",
    "Tlachichilco", "Tlalixcoyan", "Tlalnelhuayocan", "Tlaltetela",
    "Tlapacoyan", "Tlaquilpa", "Tlilapan", "Tomatlán", "Tonayán",
    "Totutla", "Tuxpan Centro", "Tuxtilla", "Úrsulo Galván",
    "Uxpanapa", "Vega de Alatorre", "Veracruz Centro", "Villa Aldama",
    "Xalapa Centro", "Xico", "Xoxocotla", "Yanga", "Yecuatla",
    "Zacualpan", "Zaragoza", "Zentla", "Zongolica", "Zontecomatlan"
  ],
  "Yucatán": [
    "Mérida", "Valladolid", "Progreso", "Tizimín", "Kanasín",
    "Umán", "Tekax", "Ticul", "Motul", "Hunucmá", "Izamal", "Chemax",
    "Abala", "Acanceh", "Akil", "Baca", "Bokobá", "Buctzotz",
    "Cacalchén", "Calotmul", "Cansahcab", "Cantamayec", "Celestún",
    "Cenotillo", "Chacsinkín", "Chankom", "Chapab", "Chemax Centro",
    "Chicxulub Pueblo", "Chichimilá", "Chikindzonot", "Chocholá",
    "Chumayel", "Conkal", "Cuncunul", "Cuzamá", "Dzan", "Dzemul",
    "Dzilam de Bravo", "Dzilam González", "Dzitás", "Dzoncauich",
    "Espita", "Halachó", "Hocabá", "Hoctún", "Homún", "Huhí",
    "Hunucmá Centro", "Ixil", "Izamal Centro", "Kaua", "Kinchil",
    "Kopomá", "Mama", "Maní", "Maxcanú", "Mayapán", "Mérida Centro",
    "Mocochá", "Muna", "Muxupip", "Opichén", "Oxkutzcab", "Panabá",
    "Peto", "Progreso Centro", "Quintana Roo", "Río Lagartos",
    "Sacalum", "Samahil", "Sanahcat", "San Felipe", "Santa Elena",
    "Seyé", "Sinanché", "Sotuta", "Sucilá", "Sudzal", "Suma",
    "Tahdziú", "Tahmek", "Teabo", "Tecoh", "Tekal de Venegas",
    "Tekantó", "Tekit", "Tekom", "Telchac Puerto", "Telchac Pueblo",
    "Temax", "Temozon", "Tepakán", "Tetiz", "Teya", "Ticul Centro",
    "Timucuy", "Tinum", "Tixcacalcupul", "Tixkokob", "Tixmehuac",
    "Tixpéhual", "Tizimín Centro", "Tunkás", "Tzucacab", "Uayma",
    "Ucú", "Umán Centro", "Valladolid Centro", "Xocchel", "Yaxcabá",
    "Yaxkukul", "Yobaín"
  ],
  "Zacatecas": [
    "Zacatecas", "Fresnillo", "Guadalupe", "Jerez", "Río Grande",
    "Sombrerete", "Pinos", "Loreto", "Ojocaliente", "Villanueva",
    "Tlaltenango", "Calera", "Jalpa", "Juan Aldama", "Juchipila",
    "Mezquital del Oro", "Miguel Auza", "Momax", "Monte Escobedo",
    "Morelos", "Moyahua de Estrada", "Nochistlán de Mejía", "Noria de Ángeles",
    "Ojos Negros", "Panuco", "Pánuco", "Valparaíso", "Villa de Cos",
    "Villa García", "Villa González Ortega", "Villa Hidalgo",
    "Apozol", "Apulco", "Atolinga", "Benito Juárez", "Chalchihuites",
    "Cuauhtémoc", "El Plateado de Joaquín Amaro", "El Salvador",
    "Genaro Codina", "General Enrique Estrada", "General Francisco R. Murguía",
    "General Joaquín Amaro", "General Pánfilo Natera", "Huanusco",
    "Jalpa Centro", "Jiménez del Teul", "Juan Aldama Centro", "Juchipila Centro",
    "Susticacán", "Tabasco", "Tepechitlán", "Tepetongo", "Teúl de González Ortega",
    "Trancoso", "Trinidad García de la Cadena"
  ],
};

export const ESTADOS = Object.keys(ESTADOS_CIUDADES).sort();
